### ISSUE TITLE
позиционирование элементво относительно родителя

### ISSUE THREAD

**Issue by Burize** [ValentinAlexandrovich/FlatUI#18]
![image](https://user-images.githubusercontent.com/22253666/33475411-eed1cbc6-d6b0-11e7-99bb-e4eef2955130.png)

Позиционирование вложенных элементов задается в родителях. Свойство  align-self получается бесполезным если у родителя не будет display: flex ...

**Comment by ValentinAlexandrovich** [comment]
![untitled](https://user-images.githubusercontent.com/31854808/33878837-2cd2e764-df5f-11e7-941e-547bb60b9b83.png)
У родителя класса (percentagesPieChart-board__wrap) имеется  имеется display: flex.
