### ISSUE TITLE
Цирфы у слайдера

### ISSUE THREAD

**Issue by Burize** [ValentinAlexandrovich/FlatUI#19]
![image](https://user-images.githubusercontent.com/22253666/33475598-908e0f24-d6b1-11e7-99bc-c3f10e3a3f3d.png)

Наверное, когда это писал, то понимал, что так не стоит делать?) - Это легко можно переделать через flex и тогда они цифр можно сколько угодно кидать (а не именно 5) и они будут выровнены всегда как надо, а не подогнаны через rem

**Comment by ValentinAlexandrovich** [comment]
Исправлено.
