### ISSUE TITLE
Добавить README

### ISSUE THREAD

**Issue by Zarwlar** [ValentinAlexandrovich/FlatUI#2]
Добавить README c описанием проекта и командами его запуска.
После этого, попробуй склонировать свой проект с гитхаба и запустить
согласно инструкции, которой ты написал.
Если всё ок - закрывай ишус

**Comment by Zarwlar** [comment]
И сразу сюда же. Нужно добавить следующие команды:
1. Команда для клонирования репозитория
2. npm i
3. a) Запуск на dev. - здесь должен запускаться какой-нибудь webpack-dev-server, например, с ключом watch
b) Получение production build'a - здесь мы должны получить, например, минифицированный css, js

**Comment by ValentinZadorozhnyy** [comment]
Исправлено.
