### ISSUE TITLE
Checkbox и Toggle

### ISSUE THREAD

**Issue by Burize** [ValentinAlexandrovich/FlatUI#21]
1) 
![image](https://user-images.githubusercontent.com/22253666/33476236-dc939b26-d6b3-11e7-9204-05a2cc147596.png)

![image](https://user-images.githubusercontent.com/22253666/33476281-fe725dd6-d6b3-11e7-8d47-9d9cdf4cd7f9.png)

Очень костыльно сделано:
1) Текущее состояние элемента (on/off) должно определяться по классу но никак не по текущему значению `right` или тем более по `color`;
2) и при клике класс у чекбокса или тоггл не меняется, то есть он статичный. Поэтому checkbox может при заданном модификаторе `_on` в любом состоянии

**Comment by ValentinAlexandrovich** [comment]
Исправлено.
