### ISSUE TITLE
.button

### ISSUE THREAD

**Issue by Zarwlar** [ValentinAlexandrovich/FlatUI#27]
В стилях этого блока у него есть такие варианты, вроде
    &-board__name
    &-board__frame
    &-content__element
Что они значат? Тебе нужно лучше разобраться в БЭМе)

**Comment by Zarwlar** [comment]
Речь идёт не только о блоке button, это затрагивает вообще все стили

**Comment by ValentinAlexandrovich** [comment]
Исправлено.
