### ISSUE TITLE
Инлайновые стили

### ISSUE THREAD

**Issue by Zarwlar** [ValentinAlexandrovich/FlatUI#28]
Зачем тут высоты и ширина заданы инлайново?
img(class="profile__foto" src=optionsInfo.link width="100%" height="100%" alt=optionsInfo.alt)

**Comment by Zarwlar** [comment]
div.profile__info(style="background:" + optionsInfo.background + "; color:" + optionsInfo.background + ";")

Нам действительно здесь необходимо инлайного разруливать задник?

**Comment by ValentinAlexandrovich** [comment]
Исправлено.
