### ISSUE TITLE
Нужно сделать более читаемо

### ISSUE THREAD

**Issue by Zarwlar** [ValentinAlexandrovich/FlatUI#31]
У тебя сейчас всё это засунуто в одну строку)
 $(this).hasClass('tickboxes__knob_on') ? $(this).addClass('tickboxes__knob_off').removeClass('tickboxes__knob_on') : $(this).addClass('tickboxes__knob_on').removeClass('tickboxes__knob_off');

**Comment by ValentinAlexandrovich** [comment]
Исправлено.
