### ISSUE TITLE
*__wrap

### ISSUE THREAD

**Issue by Zarwlar** [ValentinAlexandrovich/FlatUI#4]
Это явно костыль) Нужно сделать универсальные контейнер(ы), в которые ты будешь помещать блоки

**Comment by ValentinZadorozhniy** [comment]
Исправлено.

**Comment by ValentinZadorozhnyy** [comment]
Исправлено.

**Comment by Burize** [comment]
Подумай над его названием. В больших проекта (в наших проектах) крайне важна семантика (понимаемость кода другими людьми). Чтобы ты написал какой-нибудь элемент и другой человек, которого поставят на его доработку через месяц смог бы сразу понять что к чему. Это сократить время на выполнение  issue  и будет выгодно всем. Сейчас я думаю ты сам не вспомнишь зачем нужен `wrap` если будешь смотреть этот проект через месяц. 

Вообщем название переменных и модулей крайне важный аспект. Сергей потом еще много issue оставит по этому поводу)

**Comment by ValentinAlexandrovich** [comment]
Исправлено.
