### ISSUE TITLE
Не продемонстрирована кастомизация компонент

### ISSUE THREAD

**Issue by Zarwlar** [ValentinAlexandrovich/FlatUI#45]
Сейчас у тебя есть кастомные страницы с компонентами из UI Kit макета, но сами компоненты ты никак не изменил. Тебе нужно сделать компоненты изменяемыми (самому продумать, что и у чего должно меняться) и продемонстрировать это

**Comment by Zarwlar** [comment]
Какие-то компоненты уже являются изменяемыми, но это изменяемость не продемонстрирована

**Comment by ValentinAlexandrovich** [comment]
Исправлено.
