### ISSUE TITLE
Дефолтный options в card.pug

### ISSUE THREAD

**Issue by Zarwlar** [ValentinAlexandrovich/FlatUI#47]
Не нужно лепить его в одну строку)

**Comment by Zarwlar** [comment]
И в других компонентах также)

**Comment by ValentinAlexandrovich** [comment]
Если пререносиь на новую строку, pug  не считает ее продолжением папраметров. Как вариант могу запихнуть в миксин дефолтный опшн?

**Comment by Zarwlar** [comment]
А что именно он не считает продолжением параметров? Пробовал вот так?
`- var config = {
-     a: 'something',
-     b: 'something-else'
- }`

**Comment by ValentinAlexandrovich** [comment]
Исправлено.
