### ISSUE TITLE
Не по PerfectPixel

### ISSUE THREAD

**Issue by Zarwlar** [ValentinAlexandrovich/FlatUI#5]
Нет необходимости, чтобы макет совпадал точь-в-точь с вёрсткой, однако, каждый отдельно взятый элемент должен быть максимально похож на тот, что изображён в макете. У тебя это прослеживается не везде)
Например кнопка в единственном экземпляре подходит под макет, но ряд кнопок уже не встаёт. Или Stages - твой явно раздут :) И далее по списку)
![image](https://user-images.githubusercontent.com/26929933/31501895-b7bf6be4-af95-11e7-9e75-43d1f50c008d.png)

**Comment by ValentinZadorozhnyy** [comment]
Исправлено, прикладываю скриншоты.
![2017-11-02 15-03-14](https://user-images.githubusercontent.com/31644547/32661576-0688aff8-c65a-11e7-9efe-ed26ce4df37f.png)
![2017-11-10 15-42-24](https://user-images.githubusercontent.com/31644547/32661580-087d4eae-c65a-11e7-9433-51473d2a9289.png)
![2017-11-10 15-59-01](https://user-images.githubusercontent.com/31644547/32661585-0a46e2cc-c65a-11e7-836e-e54b7a580e4c.png)
![2017-11-10 15-42-43](https://user-images.githubusercontent.com/31644547/32661589-0b878024-c65a-11e7-89c2-3cb48197b50c.png)
![2017-11-10 15-42-51](https://user-images.githubusercontent.com/31644547/32661592-0fbacec6-c65a-11e7-9b58-0fd57e34352c.png)
![2017-11-10 15-43-35](https://user-images.githubusercontent.com/31644547/32661594-121332e4-c65a-11e7-8505-a39bad1bbde7.png)
