### ISSUE TITLE
PerfectPixel

### ISSUE THREAD

**Issue by Maksimus-Prime** [ValentinAlexandrovich/FlatUI#59]
Положи плиз картинку в проект, которую ты юзал для perfectpixel

**Comment by ValentinAlexandrovich** [comment]
Приложил, заодно прикладываю скриншоты с настройками в pixel perfect

![2018-01-26 17-22-21](https://user-images.githubusercontent.com/31854808/35435915-074bc618-02bf-11e8-970a-37d310fc1352.png)
![2018-01-26 17-22-29](https://user-images.githubusercontent.com/31854808/35435916-07891428-02bf-11e8-8df5-cb6b58c74696.png)
![2018-01-26 17-22-40](https://user-images.githubusercontent.com/31854808/35435917-07b96ace-02bf-11e8-8ba7-ede80ab5c4ee.png)
![2018-01-26 17-22-45](https://user-images.githubusercontent.com/31854808/35435918-07e58974-02bf-11e8-9d52-df6f7adacb1e.png)
![2018-01-26 17-22-48](https://user-images.githubusercontent.com/31854808/35435919-0887667c-02bf-11e8-83a7-636be0107c0f.png)
![2018-01-26 17-23-59](https://user-images.githubusercontent.com/31854808/35435920-08b2fd96-02bf-11e8-99d5-b7e9c36d49ea.png)

**Comment by ValentinAlexandrovich** [comment]
Последний скрин  для кнопок, картинка в public/img/FlatUI/FlatUI.jpg
