### ISSUE TITLE
Добавить dev скрипт

### ISSUE THREAD

**Issue by Zarwlar** [ValentinAlexandrovich/FlatUI#60]
Сейчас есть только скрипт сборки, нужно добавить скрипт для разработки, чтобы проект крутился на localhost'e

**Comment by ValentinAlexandrovich** [comment]
Исправлено.

**Comment by Zarwlar** [comment]
Нет, ты же просто изменил скрипт сборки, причём не в лучшую сторону.
Я оставил комментарий в коммите

**Comment by Zarwlar** [comment]
Т.е. тебе нужно поставить и настроить webpack-dev-server
