### ISSUE TITLE
isset

### ISSUE THREAD

**Issue by Zarwlar** [ValentinAlexandrovich/FlatUI#61]
Что это, и зачем он нужен?) Например в calendar `calendar.isset = true;`

**Comment by ValentinAlexandrovich** [comment]
Для того, чтобы Eslint не ругался.

**Comment by Zarwlar** [comment]
А на что он ругается? Этот isset же вообще нигде не используется?)

**Comment by ValentinAlexandrovich** [comment]
Если его убрать,  он говорит что переменная нигде не используется, если убрать переммную что объявлять объект нью неправильно.

**Comment by Zarwlar** [comment]
Забей, убери это) В крайнем случае можно дизейблить линтер комментариями в таких местах, ведь ты ничего криминального не совершаешь)

**Comment by ValentinAlexandrovich** [comment]
Исправлено.
