### ISSUE TITLE
CodeStyle

### ISSUE THREAD

**Issue by Zarwlar** [ValentinAlexandrovich/FlatUI#62]
Если где-то такое будет ещё встречаться, то буду скидывать сюда) Пока вот:
Перед закрывающей кавычкой лишний пробел
button.arrow(class=`arrow_${option.direction} arrow_${option.enable} `)

**Comment by Zarwlar** [comment]
$div.css({ top: `${event.pageY - $(this).offset().top}px`, left: `${event.pageX - $(this).offset().left}px` }).appendTo($(this));

Эту строку можно разбить на несколько строк

**Comment by Zarwlar** [comment]
В стилях calendar__day лишний пробел
`        padding 0.9rem 0.5rem  0 0.3rem`

**Comment by Zarwlar** [comment]
А здесь после двоеточия нужен пробел, в caption.pug
`text:"Заполните заголовок"`

**Comment by Zarwlar** [comment]
Лучше не лепить в одну строку)
this.textareaHide.append(`<div class='js-messaging__boy-message messaging__boy-message'><span class='js-messaging__boy-text messaging__boy-text'>${this.textarea.val()}</span></div>`);

**Comment by Zarwlar** [comment]
Лишний пробел
.messaging__boy-message:after
            `left  5.6rem`

**Comment by Zarwlar** [comment]
В tickboxes нужно разбить на строки 
```
if ($(this.child).hasClass('js-tickboxes__knob_on')) {
        $(this.child).addClass(`js-tickboxes__knob_off js-tickboxes__knob_${this.arrColor[0]} tickboxes__knob_off tickboxes__knob_${this.arrColor[0]}`).removeClass(`js-tickboxes__knob_on js-tickboxes__knob_${this.arrColor[1]} tickboxes__knob_on tickboxes__knob_${this.arrColor[1]}`);
      } else {
        $(this.child).addClass(`js-tickboxes__knob_on js-tickboxes__knob_${this.arrColor[1]} tickboxes__knob_on tickboxes__knob_${this.arrColor[1]}`).removeClass(`js-tickboxes__knob_off js-tickboxes__knob_${this.arrColor[0]} tickboxes__knob_off tickboxes__knob_${this.arrColor[0]}`);
      }
```

**Comment by Zarwlar** [comment]
video лишний пробел
`iframe(src=`${option.link}` width=`${option.width}`  height=`${option.height}` frameborder='0' webkitallowfullscreen mozallowfullscreen allowfullscreen)`

**Comment by Zarwlar** [comment]
В кастомных страницах везде лишний пробел
`include  ../../blocks/caption/caption`

**Comment by ValentinAlexandrovich** [comment]
Исправлено.
