### ISSUE TITLE
Нет responsive

### ISSUE THREAD

**Issue by Zarwlar** [ValentinAlexandrovich/FlatUI#71]
Согласно заданию, макет должен быть по-максимуму responsive. Сейчас это практически отсутствует
![responsive](https://user-images.githubusercontent.com/26929933/35555189-ffe2b958-05d0-11e8-838f-d00987eb553d.gif)

**Comment by ValentinAlexandrovich** [comment]
Исправлено.

**Comment by Maksimus-Prime** [comment]
Открой ишьюс, тоже самое должно быть и на кастомных страницах)

**Comment by ValentinAlexandrovich** [comment]
Исправлено.
