### ISSUE TITLE
Разделить опции, название вопроса и цвет

### ISSUE THREAD

**Issue by Znack** [ValentinAlexandrovich/FlatUI#73]
Семантически настройки дропдауна (цвет и название) принципиально отличаются от самих опций и по хорошему надо это явно в API твоего компонента показать. Ну и в целом относись к каждому компоненту как к маленькой самодостаточной библиотеке, у которой есть свои зависимости (то, что ты импортишь) и свое API :)
Тут, например, можно сделать, чтобы в дропдаун так передавлись параметры:

```
            +dropdown({
                color:'blue',
                title: "Как часто занимаетесь спортом:",
                choices: [
                  {choice: "1 раз в неделю"},
                  {choice: "2-3 раза в неделю"},
                  {choice: "4-5 раз в неделю"}
                ]
              })
```

Ну или если ты предпочитаешь везде массивы передавать в виде аргументов и потом множественные компоненты сразу рендерить, то можно массив таких объектов кидать.

**Comment by ValentinAlexandrovich** [comment]
Ага, согласен. Все исправил)

**Comment by Znack** [comment]
Только я против вот этого: `each value, option in unit` :)

Ты же можешь прямо использовать `unit.color` и `unit.title`, зачем это делать в рамках массива? :)

**Comment by ValentinAlexandrovich** [comment]
Исправил)
