### ISSUE TITLE
Мертвый компонент community-board

### ISSUE THREAD

**Issue by Znack** [ValentinAlexandrovich/FlatUI#74]
У него нет верстки и он нигде не используется

**Comment by ValentinAlexandrovich** [comment]
Оба используются, community-board => блок в основном макете, второй на страничке c обратной связью => feedback-board. Их применение укладывается в верстку при создании универсальных контейнеров для блоков во wrap-board. Старался при написании отслеживать такие моменты)

**Comment by Znack** [comment]
Я по поиску на гитхабе не смог найти :)
https://github.com/ValentinAlexandrovich/FlatUI/search?utf8=%E2%9C%93&q=community-board

Скинь плиз конкретные ссылки, где используются?

**Comment by Znack** [comment]
Если они все таки используются, то будет сразу другое замечание — блоков без html у тебя быть не может :) Так как у тебя вся иерархия создается через pug-шаблоны, так что такие блоки, где есть только стили — по сути не блоки. Их тогда надо в отдельной папке stylus-миксинами делать или еще как-нибудь выносить и чисто в стилях переиспользовать :)

**Comment by ValentinAlexandrovich** [comment]
https://github.com/ValentinAlexandrovich/FlatUI/blob/master/src/pages/feedback/feedback.pug

**Comment by ValentinAlexandrovich** [comment]
https://github.com/ValentinAlexandrovich/FlatUI/blob/master/src/pages/layout/layout.pug

**Comment by ValentinAlexandrovich** [comment]
Там пишутся класс нэйм, а создаётся все в контейнере wrap-boarf

**Comment by ValentinAlexandrovich** [comment]
https://github.com/ValentinAlexandrovich/FlatUI/blob/master/src/blocks/wrap-board/wrap-board.pug

**Comment by ValentinAlexandrovich** [comment]
Т.е. тут лучше миксинить их в стили из папки стайлус, верно?)

**Comment by Znack** [comment]
Лучше из стайлуса да напрямую. Только я все равно не нашел, как применяешь. Скинь сюда прямо сниппет, вот как в гитхабе делается: https://help.github.com/articles/creating-a-permanent-link-to-a-code-snippet/

**Comment by ValentinAlexandrovich** [comment]
https://github.com/ValentinAlexandrovich/FlatUI/blob/98e85957207969a4870b3c7cfecf2e966abe5f58/src/pages/layout/layout.pug#L90
это для community-board

https://github.com/ValentinAlexandrovich/FlatUI/blob/98e85957207969a4870b3c7cfecf2e966abe5f58/src/pages/feedback/feedback.pug#L16
это для feedback-board

Изначально они передаются в classname как community и feedback, а затем преобразуются вот здесь https://github.com/ValentinAlexandrovich/FlatUI/blob/98e85957207969a4870b3c7cfecf2e966abe5f58/src/blocks/wrap-board/wrap-board.pug#L8 уже в community-board, feedback-board

в верстке они по поиску находтся вот здесь https://github.com/ValentinAlexandrovich/FlatUI/blob/98e85957207969a4870b3c7cfecf2e966abe5f58/public/layout.html#L1 
это для community-board

https://github.com/ValentinAlexandrovich/FlatUI/blob/98e85957207969a4870b3c7cfecf2e966abe5f58/public/feedback.html#L1 это для feedback-board

**Comment by Znack** [comment]
Ааа, у тебя так было сделано :) Ну на самом деле это плохой подход, вот даже тот факт, что хрен найдешь использования и что все очень неочевидно для входящего в проект человека говорит о как минимум одной серьезной проблеме :)
Ну и в целом у нас в стандартах запрос на использование миксинов, а тут как раз такой случай, по сути ты передаешь имя класса в параметрах — а это ужасный моветон :)

**Comment by ValentinAlexandrovich** [comment]
Стоит разбить на миксин wrap board на отдельные блоки?

**Comment by Znack** [comment]
На самом деле мне сложно сказать, я не вдавался в детали задачи этой и как сейчас устроено :)

Так что либо тебе самому что-то сделать и показать, либо мне тут максимально подробно и полно все описать, чтобы я по описанию смог совет дать

**Comment by ValentinAlexandrovich** [comment]
Хорошо, я разобью чтобы это было очевидным блоком. Это ишью на самом деле минут на 15 работы вечером. Можно попросить тебя, если больше ишьюсов нет по макетам, то глянуть еще игру?

**Comment by Znack** [comment]
У нас на носу большой деплой, я пока не могу выделить разом больше 2-х минут, так что скорее всего на выходных гляну :)

Пока готовься к собесу, чтобы потом сразу к нему приступить. Очень советую все детально и подробно изучить, потому что мы будем требовать хорошо подготовленных осознанных ответов :)

**Comment by ValentinAlexandrovich** [comment]
Внес изменения, избавился от неявностей с мертвыми блоками :)

**Comment by Znack** [comment]
Ух, у тебя сейчас целая куча дубликаций кода, есть ли вариант это убрать? :) В принципе если не будет, то можно закрыть ишью

**Comment by ValentinAlexandrovich** [comment]
Только тот, что оказался моветоном 😔

**Comment by ValentinAlexandrovich** [comment]
Думал над способами, когда правил ишью, но лучше придумать не удалось. Ок, тогда закрываю.
