### ISSUE TITLE
Передача всех парамеров во все компонеты в виде массива?

### ISSUE THREAD

**Issue by Znack** [ValentinAlexandrovich/FlatUI#75]
Тут очень спорный момент, почему все компоненты принимают массивы параметров и внутри бегают по ним циклом для рендера множественных эдементов. Можешь плиз объяснить, почему хотел так сделать? :) Я потом напишу, какие еще есть варианты :)

**Comment by ValentinAlexandrovich** [comment]
Да, конечно. Это было сделано, чтобы рендерить в макете,  необходимое количество блоков (поскольку там онисгруппированы вместе), а затем разносить их, как потребуется с помощью флексбоксов в родительских блоках.

**Comment by Znack** [comment]
На самом деле, мне кажется это плохая идея :) Это усложняет API твоих компонент, делает его излишним. По сути сам механизм компонент через pug-шаблоны позволяет рендерить любое кол-во экземлпяров компонент тупо нужным кол-вом вызовов твоих pug-миксинов :)
Но здесь я понимаю, что сейчас это проблем не несет, и тебе очень долго придется переделывать, поэтому можно забить. Но на будущее старайся таких кривых API у твоих модулей не делать :)
