### ISSUE TITLE
jQuery переменные должны начинаться с $

### ISSUE THREAD

**Issue by Znack** [ValentinAlexandrovich/FlatUI#76]
```
this.day = $(this.domElement).find('.js-calendar__day');
this.widget = $(this.domElement).find('.js-calendar__path');
```

здесь, например, тоже должны быть `this.$day`; `this.$widget`

**Comment by Znack** [comment]
Это правило надо еще по всему проекту проверить, может еще где-нибудь косяки есть (как минимум кстати `this.domElement` надо везде в `this.$domElement` переименовать :0

**Comment by ValentinAlexandrovich** [comment]
Исправил переменные)
