### ISSUE TITLE
Селектить только элементы внутри блока, а не вообще все с заданным классом

### ISSUE THREAD

**Issue by Znack** [ValentinAlexandrovich/FlatUI#77]
У тебя сейчас есть вот такой код в коде кнопки:

```
$('.js-button_ripple-effect.button_ripple-effect').css('height', $(this).height());
```
Тут не гарантируется, что не будут затронуты соседние кнопки и твоя абстракция может "потечь", такого лучше избегать. Вообще везде в комопнентах надо селектить элементы из DOM-a только через `this.$domElement.find(...)` — только тогда ты можешь быть уверен, что у тебя действие по одному компоненту на странцие не будет влиять на все остальные компоненты. Тут у тебя причем интересный случай, когда чисто технически очень вряд ли юзер будет способен спровоцировать такую ошибки и заметить ее. Но все же всегда на делать так, чтобы у тебя наверняка не возникали описанные мною выше конфликты из-за селекторов :) Поэтому просто все селекти только через `this.$domElement.find(...)`

**Comment by Znack** [comment]
Ну и по проекту в целом пробегись, исправь, если есть еще подобные косяки

**Comment by Znack** [comment]
Вот, нашел огромный косяк в form.js, в функции `initEvent`. Получается, при каждом создании формы вообще во всех формах будут стираться сообщения thanks & errors. У тебя такой ошибки не наблюдалось, потому что ты все формы сразу при старте проекта инициировал, но представь формы, которые динамически добавляются посреди работы пользователя (например, при открытии вкладки как в сообщения Вконтакте, внутри которой будет диалог с пользователем и форма, а при переключении диалога форма тоже будет перерендирваться).

**Comment by ValentinAlexandrovich** [comment]
Спасибо за ценные и главное подробные замечания) Подправил код, нашел еще в пару местах подобное.

**Comment by ValentinAlexandrovich** [comment]
Ага, спасибо - не доглядел)
