### ISSUE TITLE
А что такое button.isset = 'true'?

### ISSUE THREAD

**Issue by Znack** [ValentinAlexandrovich/FlatUI#78]
Не смог понять смысла этой строки в button.js :)

**Comment by Znack** [comment]
marker.isset = true;

**Comment by ValentinAlexandrovich** [comment]
Убрал из кода, это было из за правила no-new в Eslinte, чтобы обойти его создавал инстанс присваивая константе, затем Eslint ругался, что объект не юзается, поэтому добавлял ему поле что он существует .isset = true. Сейчас просто отключил это правило)
