### ISSUE TITLE
Нет части макета

### ISSUE THREAD

**Issue by Zarwlar** [ValentinAlexandrovich/FlatUI#8]
![image](https://user-images.githubusercontent.com/26929933/31502378-14dda7fe-af97-11e7-9314-f091b59e39b0.png)
У полей должны быть надписи ERROR и THANKS

**Comment by ValentinZadorozhnyy** [comment]
Error и Thanks появляются при нажатии кнопки submit с валидацией вводимых данных.

**Comment by Zarwlar** [comment]
Ладно, но это не очевидно с точки зрения ux) Мне приходится сабмитить форму для того, чтобы проверить, корректно ли я заполнил поля)

**Comment by ValentinZadorozhnyy** [comment]
Исправлено, сделал чтобы появлялся контент при введении информации в поле, без нажатия на submit.
