### ISSUE TITLE
Избегать лишний мутаций компонентов через методы

### ISSUE THREAD

**Issue by Znack** [ValentinAlexandrovich/FlatUI#80]
В stages.js у тебя хороший пример плохого ООП :)

У тебя есть инстанс компоненты Stages, потом ты вызываешь метод initStages и в нем бегаешь по значкам. Только ты зачем-то делаешь в каждом шаге присваивание this.child, и тут как минимум две большие проблемы:
— семантически Stages вообще не может иметь такого свойства как child, потому что у него много потомков, а не один. И очень странно там держать одного какого-то потомка, потому что сейчас какой-то одной функции он нужен. Если он нужен функциям — пусть они его найдут и напрямую использовать, но не засоряют свойства самого компонента
— у тебя вот в таком коде прослеживается одна из главных проблем ООП:
```
    for (let i = 1; i <= this.progressbarStage; i += 1) {
      this.findSiblings(`.js-stages__point_${i}.stages__point_${i}`);
      $(this.child).css({ color: '#ffffff;', 'background-color': '#e75735;' });
    }
```
Здесь ты вызываешь this.findSiblings и надеешься, что будет правильно смутирован this и на следующей строке кода ты будешь иметь желаемый элемент в this.child. Получается, что инкапсуляции метода this.findSiblings полностью нарушена, так как ты вот тут извне надеешься на внутреннее устройство this.findSiblings (надеясь, что там будет мутация this причем нужная тебе). 

Поэтому лучше явно использовать простые функции, которые принимают параметры, возвращают результаты и ничего не мутируют :) В данном случае просто можно из findSiblings возвращать результаты поиска, а не записывать в this.child

Очень советую тут хорошо разобрать мои аргументы, позадавать вопросы и тд, потому что это очень важный момент. По-хорошему еще почитать что-нибудь про основные проблемы ООП, таких статей довольно много и это будет крайне полезно :)

**Comment by ValentinAlexandrovich** [comment]
Да, здесь согласен по всем пунктам, и о том что инкапсуляция метода пропадает, и то что происходит мутация инстанса, чего вполне можно избежать. Спасибо за наставления, буду придерживаться этого правила)

**Comment by Znack** [comment]
Ну ты кстати почитал что-нибудь про основные проблемы в ООП? :)

**Comment by ValentinAlexandrovich** [comment]
Ага, вот эту статейку) https://habrahabr.ru/post/149096/
