### ISSUE TITLE
Править код вендоров аккуратно

### ISSUE THREAD

**Issue by Znack** [ValentinAlexandrovich/FlatUI#82]
Нашел у тебя коммит,где ты в код вендора (`src/vendor/radialIndicator/radialIndicator.js`) добавил 

```
return can.classList.add("js-percentages__round", "percentages__round");
```
Но это явно не должно быть в вендоре. Ты по сути сразу обрезал все возможности переиспользовать эту библиотеку. Вообще править код вендоров это жуткий моветон. Лучше это делать путем форкания библиотеки, явного оформления всех правок в коммиты в отдельном репозитории, заведении ишью в лсновном проекте и создании pull request-ов туда. Так что тут я бы вообще советовал ничего не редактировать

**Comment by ValentinAlexandrovich** [comment]
Исправил это ишью по пути с предыдущим)
